version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
