version: '3'

services:
  frontend:
    image: frontWebApp:latest  
    ports:
      - "80:80"  
    depends_on:
      - backend  
    environment:
      - BACKEND_URL=http://backend:80  

  users:
    image: users:latest
    ports:
      - "8000:80"  
    depends_on:
      users_db:
        condition: service_healthy
    environment:
      - DB_USER=prueba
      - DB_PASSWORD=prueba
      - DB_HOST=db  
      - DB_NAME=prueba
      - DB_PORT=5432
      - AUTH0_DOMAIN=dev-s8qwnnguwcupqg2o.us.auth0.com
      - AUTH0_CLIENT_SECRET=SnUDnO1lL3CnvzeCDFFUwwsFABY-Szfr-lRkFyshOf4uSnCiM6EHMgvCDDVQ8v1u
      - AUTH0_CLIENT_ID=3H1DJStRDxr7jeKsxyvsPEe2Af8BpUcT
      - REDIRECT_URI=http://127.0.0.1:8000/callback/
      - AUTH0_API_IDENTIFIER=https://dev-s8qwnnguwcupqg2o.us.auth0.com/api/v2/
      - ALGORITHM=RS256
      - DATABASE_URL=postgresql://prueba:prueba@db:5432/prueba

  users-db:
    image: postgres:latest  
    environment:
      - POSTGRES_DB=prueba  
      - POSTGRES_USER=prueba  
      - POSTGRES_PASSWORD=prueba  
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
