  version: '3'

  services:
    prueba:
      image: postgres:latest
      environment:
        POSTGRES_DB: prueba
        POSTGRES_USER: prueba
        POSTGRES_PASSWORD: prueba
      ports:
        - "5435:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    # web:
    #   build: .
    #   command: uvicorn --host 0.0.0.0 --port 80 main:app
    #   volumes:
    #     - .:/app
    #   ports:
    #     - "80:80"
    #   depends_on:
    #     - prueba
    #   environment:
    #     - DB_USER=prueba
    #     - DB_PASSWORD=prueba
    #     - DB_HOST=prueba
    #     - DB_NAME=prueba
    #     - DB_PORT=5432
    #     - AUTH0_DOMAIN=dev-s8qwnnguwcupqg2o.us.auth0.com
    #     - AUTH0_CLIENT_SECRET=SnUDnO1lL3CnvzeCDFFUwwsFABY-Szfr-lRkFyshOf4uSnCiM6EHMgvCDDVQ8v1u
    #     - AUTH0_CLIENT_ID=3H1DJStRDxr7jeKsxyvsPEe2Af8BpUcT
    #     - REDIRECT_URI=http://127.0.0.1:8000/callback/
    #     - AUTH0_API_IDENTIFIER=https://dev-s8qwnnguwcupqg2o.us.auth0.com/api/v2/
    #     - ALGORITHM=RS256
    #     - DATABASE_URL=postgresql://prueba:prueba@prueba:5432/prueba

  volumes:
    postgres_data:
