version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: entrenamiento
      POSTGRES_PASSWORD: prueba
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"

  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: prueba
      DB_PORT: 5432
      DB_ENTRENAMIENTO: entrenamiento
      DB_PASSWORD: prueba
    volumes:
      - ./app:/code/app  
