version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    # depends_on:
    #   - users
    environment:
      - BACKEND_URL=http://backend:80
