version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    depends_on:
      - db
    environment:
      DB_USER: prueba
      DB_PASSWORD: prueba
      DB_HOST: localhost
      DB_NAME: prueba
      DB_PORT: 5432
    volumes:
      - ./app:/code/app