version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3007:3007"
#     depends_on:
#       - db
#     environment:
#       DB_USER: prueba
#       DB_PASSWORD: prueba
#       DB_HOST: db
#       DB_NAME: prueba
#       DB_PORT: 5432
#     volumes:
#       - ./app:/code/app
