version: "3"
services:
  # db:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_USER: example
  #     POSTGRES_DB: example
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   ports:
  #     - "5003:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 60s
  #     retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    # depends_on:
    #     db:
    #       condition: service_healthy
    # environment:
    #   DB_USER: example
    #   DB_PASSWORD: example
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_NAME: example
    #   DATABASE_URL: postgresql://example:example@db/example