### Automatización de merging de ramas feature/** que se van a integrar con la rama develop.
name: Feature
on:
  push:
    branches:
      - 'feature**'

jobs:
  # Parte de Feature:
  # Integra las ramas develop -> feature.
  # La palabra clave que activa el merge a develop es "(azul)".
  automerge-1:
    name: Merge 'develop -> feature'
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '(azul)') }}
    outputs:
      salida: ${{ steps.prepare_release.outputs.respuesta }}
    steps:
      - name: Integrar develop en feature
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}
          commit-message: "Actualizar rama feature con respecto a rama develop"
      - name: prepare_release
        id: prepare_release
        run: |
          echo "::set-output name=respuesta::$(echo "${{ github.event.head_commit.message }}" | awk '{print $NF}')"

  # Luego de integrar con develop, corre las pruebas de cobertura.
  # Si pasan bien, integra feature a develop.
  # Si fallan, no integra y falla el job.
  run-tests-1:
    name: Integration tests
    runs-on: ubuntu-latest
    services:
      users:
        image: postgres
        env:
          POSTGRES_PASSWORD: prueba
          POSTGRES_USER: prueba
          POSTGRES_DB: prueba
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5    
    needs: 'automerge-1'
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4
      - name: Configuracion de entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up environment variables for dev
        run: |
          export AUTH0_CLIENT_ID= ${{ secrets.AUTH0_CLIENT_ID }}
          export AUTH0_CLIENT_SECRET= ${{ secrets.AUTH0_CLIENT_SECRET }}
          export AUTH0_DOMAIN= ${{ secrets.AUTH0_DOMAIN }}
          export AUTH0_API_IDENTIFIER= ${{ secrets.AUTH0_API_IDENTIFIER }}
          export ALGORITHM= ${{ secrets.ALGORITHM }}
      - name: Install Dependencies
        working-directory: ./backend/services/users
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start FastAPI App
        working-directory: ./backend/services/users
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
      - name: Run Tests
        working-directory: ./backend/services/users
        run: |
          coverage run -m pytest tests/* -v
      - name: Run cov report
        working-directory: ./backend/services/users
        run: |
          coverage report --fail-under=70

  # Luego de pruebas exitosas, integra las ramas.
  # feature -> develop
  automerge-2:
    name: Merge 'feature -> develop'
    runs-on: ubuntu-latest
    needs: 'run-tests-1'
    steps:
      - name: Integrar feature en develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop
          commit-message: "Integrar rama feature en develop (crearRelease)"