### Automatización de merging de ramas feature/** que se van a integrar con la rama develop.
name: Feature
on:
  push:
    branches:
      - 'feature**'

jobs:
  pre-run:
    name: Pre-integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuracion de entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

  # Integra las ramas develop -> feature.
  automerge-1:
    name: Merge 'develop -> feature'
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.prepare_release.outputs.respuesta }}
    # La palabra clave que activa el merge a develop es "(azul)".
    if: ${{ contains(github.event.head_commit.message, '(azul)') }}
    needs: pre-run
    steps:
      - name: Integrar develop en feature
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}
          commit-message: "Actualizar rama feature con respecto a rama develop"
      - name: prepare_release
        id: prepare_release
        run: |
          echo "::set-output name=respuesta::$(echo "${{ github.event.head_commit.message }}" | awk '{print $NF}')"

  # Luego de integrar con develop, corre las pruebas de cobertura.
  # Si pasan bien, integra feature a develop.
  # Si fallan, no integra y falla el job.
  run-tests-1:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: 'automerge-1'
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuracion de entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Instalacion de librerias y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python3 -m unittest discover -s tests -v
      - name: Calculo de cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m

  # Luego de pruebas exitosas, integra las ramas.
  # feature -> develop
  automerge-2:
    name: Merge 'feature -> develop'
    runs-on: ubuntu-latest
    needs: 'run-tests-1'
    steps:
      - name: Integrar feature en develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop
          commit-message: "Integrar rama feature en develop (crearRelease)"