### Automatización de merging de ramas feature/** que se van a integrar con la rama develop.
name: Feature
on:
  push:
    branches:
      - 'feature**'

jobs:
  # Integra las ramas develop -> feature.
  # La palabra clave que activa el merge a develop es "(azul)".
  automerge-1:
    name: Merge 'develop -> feature'
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '(azul)') }}
    outputs:
      salida: ${{ steps.prepare_release.outputs.respuesta }}
    steps:
      - name: Integrar develop en feature
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}
          commit-message: "Actualizar rama feature con respecto a rama develop"
      - name: prepare_release
        id: prepare_release
        run: |
          echo "::set-output name=respuesta::$(echo "${{ github.event.head_commit.message }}" | awk '{print $NF}')"

  # Luego de integrar con develop, corre las pruebas de cobertura.
  # Si pasan bien, integra feature a develop.
  # Si fallan, no integra y falla el job.
  run-tests-1:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: 'automerge-1'
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4
      - name: Configuracion de entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Espacio para poner las pruebas de cobertura...
#      - name: Instalacion de librerias y dependencias
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Correr pruebas
#        id: correr-pruebas
#        run: python3 -m unittest discover -s tests -v
#      - name: Calculo de cubrimiento
#        id: cubrimiento
#        run: |
#          coverage run -m unittest discover -s tests -v
#          coverage report -m

  # Luego de pruebas exitosas, integra las ramas.
  # feature -> develop
  automerge-2:
    name: Merge 'feature -> develop'
    runs-on: ubuntu-latest
    needs: 'run-tests-1'
    steps:
      - name: Integrar feature en develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop
          commit-message: "Integrar rama feature en develop (crearRelease)"

  # La palabra clave que activa el job es "(crearRelease)".
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '(crearRelease)') }}
    outputs:
      salida: ${{ steps.prepare-release.outputs.respuesta }}
    steps:
      - name: prepare-release
        id: prepare-release
        run: |
          echo "::set-output name=respuesta::$(echo "${{ github.event.head_commit.message }}" | awk '{print $NF}')"

  # Se crea la rama release.
  crear-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: 'prepare-release'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.outputs.salida }}
          release_name: ${{ needs.prepare-release.outputs.salida }}
          draft: false
          prerelease: false
      - name: Crear rama
        run: |
          git checkout -b release/${{ needs.prepare-release.outputs.salida }}
          git push -f -u origin release/${{ needs.prepare-release.outputs.salida }}