### Automatización de merging de la rama develop que se va a integrar con la rama main.
name: Release
on:
  push:
    branches:
      - 'develop'

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    # La palabra clave que activa el job es "(crearRelease)".
    if: ${{ contains(github.event.head_commit.message, '(crearRelease)') }}
    outputs:
      salida: ${{ steps.prepare-release.outputs.respuesta }}
    steps:
      - name: prepare-release
        id: prepare-release
        run: |
          echo "::set-output name=respuesta::$(echo "${{ github.event.head_commit.message }}" | awk '{print $NF}')"

  # Se crea la rama release.
  crear-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: 'prepare-release'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.outputs.salida }}
          release_name: ${{ needs.prepare-release.outputs.salida }}
          draft: false
          prerelease: false
      - name: Crear rama
        run: |
          git checkout -b release/${{ needs.prepare-release.outputs.salida }}
          git push -f -u origin release/${{ needs.prepare-release.outputs.salida }}

  # Hacer pull de develop para traer los últimos cambios
  pull-develop:
    name: Pull develop
    runs-on: ubuntu-latest
    needs: 'crear-release'
    steps:
      - name: Integrar feature en develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: develop

  # Luego de crear rama release se integra con develop.
  # develop -> release
  automerge-3:
    name: Merge 'develop -> release'
    runs-on: ubuntu-latest
    needs: [ pull-develop, prepare-release ]
    steps:
      - name: Integrar release a develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: release/${{ needs.prepare-release.outputs.salida }}
          commit-message: "Integrar rama release con develop"

  # Se ejecutan las pruebas.
  # Si pasan bien, se mezcla release en main.
  # Si fallan, no se mezcla y falla el job.
  run-tests-2:
    name: Pre-integration tests
    runs-on: ubuntu-latest
    needs: 'automerge-3'
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuracion de entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Instalacion de librerias y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python3 -m unittest discover -s tests -v
      - name: Calculo de cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m

  # Luego de pruebas exitosas, integra las ramas.
  # release -> main
  automerge-4:
    name: Merge 'release -> main'
    runs-on: ubuntu-latest
    needs: [ run-tests-2, prepare-release ]
    steps:
      - name: Integrar release en main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release/${{ needs.prepare-release.outputs.salida }}
          target-branch: main
          commit-message: "Integrar rama release en main"