name: Terraform
on:
  workflow_call:

inputs:
  # Tus variables de entrada
  # El folder del codigo
  terraform_directory:
    type: string
    description: 'Terraform infrastructure folder'
    required: true

secrets:
  aws_access_key_id:
  aws_secret_access_key:

defaults:
  run:
  working_directory: ${{ inputs.terraform_directory }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key}}
  # El otro también lo pones

jobs:
  terraform_reusable_workflow:
    steps:
      - name: Terraform init
        runs: |
          terraform init
          terraform plan
          terraform apply --auto-approve
