name: coverage
on:
  push:
    branches:
      - 'develop'
jobs:
  run-tests-apigateway:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_API_IDENTIFIER: ${{ secrets.AUTH0_API_IDENTIFIER }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4
      - name: Configuracion de entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        working-directory: ./backend/services/apigateway
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        working-directory: ./backend/services/apigateway
        run: |
          coverage run -m pytest tests/* -v
      - name: Run cov report
        working-directory: ./backend/services/apigateway
        run: |
          coverage report --fail-under=55
          pytest --cov . --cov-report=xml:apigateway_coverage.xml
          
  build:
    runs-on: ubuntu-latest
    name: Test python API
    needs: [run-tests-apigateway]
    steps:
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        